### ISSUE TITLE
MDB protocol?

### ISSUE THREAD

**Issue by beckmx** [Lauszus/ArduinoVendingMachine#4]
Hello guys, I was wondering if the main arduino uses mdb protocol to connect to the coin validator

**Comment by Jervelund** [comment]
The old coin validator used some sort of bus to connect to the control
unit. The one we use now just sends a number of pulses for each coin. It's
configurable how many pulses it should send for any given type of coin. We
use 2 pulses for 5kr, 4 pulses for 10kr and 8 pulses for 20kr, as that
makes it easy to translate two pulses into 5kr.

We could also have used 1pulse =5kr, but we have a a lot of grounding
issues, so that didn't work that well.

There's a blog post with some more info
http://blog.tkjelectronics.dk/2015/02/iot-arduino-vending-machine/

**Comment by beckmx** [comment]
I am having trouble with this MDB protocol of hell :s

2016-01-14 18:47 GMT-06:00 Sigurd Jervelund Hansen <notifications@github.com

> :
> 
> The old coin validator used some sort of bus to connect to the control
> unit. The one we use now just sends a number of pulses for each coin. It's
> configurable how many pulses it should send for any given type of coin. We
> use 2 pulses for 5kr, 4 pulses for 10kr and 8 pulses for 20kr, as that
> makes it easy to translate two pulses into 5kr.
> 
> We could also have used 1pulse =5kr, but we have a a lot of grounding
> issues, so that didn't work that well.
> 
> There's a blog post with some more info
> http://blog.tkjelectronics.dk/2015/02/iot-arduino-vending-machine/

**Comment by Lauszus** [comment]
@beckmx since we haven't used it I am closing this issue. I have never worked with MDB, so I am afraid that I can not be of much help.
